spring.application.name=Secure Vault


#Database Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/securevault
spring.datasource.username=root
spring.datasource.password=qwerty
spring.jpa.show-sql=true

#Auth Config
jwt.secret=aK8O44ZO3WntAHO+ArNlxt3d5y87cwqj1C7uZBpJ9I0=
jwt.expiration=3000
jwt.refreshExpiration=200