name: GitHub Action

on:
  push:
    branches: ["main", "dev/userservice", "dev/paymentservice"]

  workflow_dispatch:

jobs:
  print-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print README.md
        run: cat README.md